import { Shark } from "./Fish";
import { Dolphin } from "./Fish";
import { Coffee } from "./Drink";
import { Juice } from "./Drink";
import { Airplane, Helicopter } from "./Aircraft";
import { Guitar, Piano } from "./Instrument";
import { Pizza, Sushi } from "./Food";
import { EmailNotification, PushNotification, SMSNotification } from "./Notification";
import { Refrigerator, WashingMachine, Microwave } from "./Appliance";
console.log("*************************** Shark *************************************")
const shark1 = new Shark("White Shark", "Sphyrna zygaena", "Special Electroreceptor Organs")
console.log(shark1.toString())
shark1.swim()
shark1.bloodSeeker()
console.log("**********************************************************************")
console.log("*************************** Dolphin *************************************")
const dolphin1 = new Dolphin("Pink Dolphin", "Inia geoffrensis", "Supersonic Sound Underwater")
console.log(dolphin1.toString())
dolphin1.swim()
dolphin1.splitWater()
console.log("**********************************************************************")
const coffee1 = new Coffee("Americano")
console.log(coffee1.toString())
coffee1.addMilk()
coffee1.serve()
const juice1 = new Juice("Apple Juice")
console.log(juice1.toString())
juice1.addWatermelon()
juice1.serve()
console.log("*************************** Helicopter *************************************")
const helicopter1 = new Helicopter("Bell Boeing V-22 Osprey", 2)
console.log(helicopter1.toString())
helicopter1.shootGatling()
helicopter1.fly()
console.log("*************************** Airplane *************************************")
const airplane1 = new Airplane("Thai Lion Air B737-800", 189)
console.log(airplane1.toString())
airplane1.controlTemparature()
airplane1.fly()
console.log("**********************************************************************")
console.log("*************************** Instrument *************************************")
const guitar1 = new Guitar("Eletric Guitar")
console.log(guitar1.toString())
guitar1.play()
guitar1.strummingGuitar()
const piano1 = new Piano("Classic Piano")
console.log(piano1.toString())
piano1.play()
piano1.pressPiano()
console.log("*********************************************************************************")
console.log("*************************** Food *************************************")
const pizza1 = new Pizza("Deluxe Pepperoni Pizza")
pizza1.serve()
pizza1.addCheese()
const sushi1 = new Sushi("Sushi Salmon Rolled")
sushi1.serve()
sushi1.addWasabi()
console.log("************************************************************************")
console.log("*************************** Notification *************************************")
const emailNotification1 = new EmailNotification("ChatGPT outdated today")
const smsNotification1 = new SMSNotification("Your Phone Number is expeiring in 2 days")
const pushNotificatiob1 = new PushNotification("99+ Message You haven't read.")
emailNotification1.send("ChatGPT outdated today Nowadays There are many AI for generated for work or something more")
smsNotification1.send("Please Pay The Bill.")
pushNotificatiob1.send("Click To View Details.")
console.log("********************************************************************************")
console.log("*************************** Appliance *************************************")
const washingmachine1 = new WashingMachine("Mitsubishi Electric Washing Machine")
const refrigerator1 = new Refrigerator("LG Bottom-Freezer Refrigerators")
const microwave1 = new Microwave("SAMSUNG ไมโครเวฟ SOLO Pure White")
console.log(washingmachine1.toString())
washingmachine1.turnOff()
washingmachine1.turnOn()
console.log(refrigerator1.toString())
refrigerator1.turnOff()
refrigerator1.turnOn()
console.log(microwave1.toString())
microwave1.turnOff()
microwave1.turnOn()
console.log("********************************************************************************")